### ISSUE TITLE
Doesn't work with german level names

### ISSUE THREAD

**Issue by StenApp** [JulianOzelRose/TR-SaveMaster#1]
Doesn't work with german level names.

I'm using https://github.com/Trxyebeep/tomb3

**Comment by JulianOzelRose** [comment]
Hi, I just added German level name strings to the editor. The updated binary is [here](https://github.com/JulianOzelRose/TR-SaveMaster/tree/master/TR-SaveMaster/bin/x64/Release). Let me know if it works.

**Comment by StenApp** [comment]
It recognizes the level names without umlauts like Tempelruine.
Kaliya Höhlen, in hexeditor Kaliya H~ohlen, these savegames are not present in the save game editor.

**Comment by StenApp** [comment]
TR2 with https://github.com/Arsunt/TR2Main
same thing "Die Gro=e Mauer"

"

**Comment by JulianOzelRose** [comment]
I don't have access to any German savegames. What do the level strings that contain "ü" appear as in a hex editor for TR3?

**Comment by StenApp** [comment]
> I don't have access to any German savegames. What do the level strings that contain "ü" appear as in a hex editor for TR3?

It appears as K~ustendorf

**Comment by JulianOzelRose** [comment]
Updated for German level names for TR3 and TR2. Let me know if it works.

**Comment by StenApp** [comment]
TR1
- gog version dosbox with 3dfx [SAVEGAME.0.txt](https://github.com/JulianOzelRose/TR-SaveMaster/files/14028297/SAVEGAME.0.txt)  Die Kavernen
- tombatiDE [saveati.0.txt](https://github.com/JulianOzelRose/TR-SaveMaster/files/14028290/saveati.0.txt) Die Kavernen
- TR1X https://github.com/LostArtefacts/TR1X [save_tr1_00.dat.txt](https://github.com/JulianOzelRose/TR-SaveMaster/files/14028060/save_tr1_00.dat.txt) different file format?
- TR1X unfinished business 
[save_trub_00.dat.txt](https://github.com/JulianOzelRose/TR-SaveMaster/files/14028089/save_trub_00.dat.txt)

TR2 https://github.com/Arsunt/TR2Main Golden Mask savegame.0 Der kalte Krieg
TR3 https://github.com/Trxyebeep/tomb3 Lost artifact different file format? [savegame.0.txt](https://github.com/JulianOzelRose/TR-SaveMaster/files/14028145/savegame.0.txt)

TR4 https://github.com/Trxyebeep/TOMB4 hexvalue Angkor Wat
TR5 https://github.com/Trxyebeep/TOMB5  hexvalue Die Strassen von Rom

TR3 has problems with ü and ö
<img width="492" alt="2024-01-23 19_07_00-HxD -  C__Spiele_TR3_saves_savegame 14" src="https://github.com/JulianOzelRose/TR-SaveMaster/assets/32524257/820ea586-2e7f-4e40-8323-f02c2d94d885">
<img width="483" alt="2024-01-23 19_07_30-HxD -  C__Spiele_TR3_saves_savegame 6" src="https://github.com/JulianOzelRose/TR-SaveMaster/assets/32524257/67ccc154-d934-4ea0-804a-8a91c22d541b">

Is there a way to compile a list with level names in german without playing through every level?

**Comment by JulianOzelRose** [comment]
TR1
- Should now read German level names
- Should now work with ATI and GOG savegame formats

The Golden Mask
- Should now read German level names

TR3
- Should now properly read German level names with umlauts

TR4
- Should now read German level names

TR5
- Should now read German level names

For compiling German level names, I just used DE wikis and some YouTube playthroughs. For special characters like umlauts, I made an assumption that they are formatted in the same way as in TR3 ('~' before a character indicates it has umlaut, and '=' indicates 'ß' character) but it may not necessarily work this way, in which case you can provide me with the non-working file(s) and I will adjust it.

For the TLA savegame you provided, it seems to use the same format, but the level strings are a bit different (i.e. "Highlands" instead of "Highland Fling"). If you could provide some more savegames for the other levels, I will make my editor compatible with it.

Lastly, TR1X appears to use a completely different format for its savegames. To support those, you would likely have to build an entirely separate editor specifically for it.

Let me know how this all works, and I will package it as a new release if everything is good.

**Comment by StenApp** [comment]
Thank you for your hard work, i'm going to test it and report here.

**Comment by JulianOzelRose** [comment]
Sure thing. I just updated the editor to use the level index instead of level string to determine parameters/offsets, so it should work with any level string/language now. Let me know if it works with GOG and ATI savegames.

**Comment by StenApp** [comment]
I get a crash if i select the wrong folder for the game tab i opened
[Crash of picking wrong TR game folder.txt](https://github.com/JulianOzelRose/TR-SaveMaster/files/14057855/Crash.of.picking.wrong.TR.game.folder.txt)

**Comment by StenApp** [comment]
- Selecting UB tab with TombAtiDE UB (was gog,, TombAti expanded it with UB missions) i see saveati.0 and saveuba.0 (both in root of TR1), i only see saveati.0 in TR1 tab
- TR1 GoG (dosbox version :-( )works, expansion not possible to test, its missing from the gog version
- the rest looks good, cannot test TR2 and TR3 GoG with expansions, only by Tr2Main and Tomb3 mods, those work

**Comment by JulianOzelRose** [comment]
I patched it to no longer crash when trying to load the wrong directory. If you send me an archive of the GOG/ATI savegame files that aren't displaying for TR1/UB, I can check them out. I have a feeling I know why it's happening.

**Comment by StenApp** [comment]
Both save file types are stored in root of Tomb Raider 1 ATI [Tomb Raider 1 ATI.rar.txt](https://github.com/JulianOzelRose/TR-SaveMaster/files/14067505/Tomb.Raider.1.ATI.rar.txt)

**Comment by JulianOzelRose** [comment]
> Both save file types are stored in root of Tomb Raider 1 ATI [Tomb Raider 1 ATI.rar.txt](https://github.com/JulianOzelRose/TR-SaveMaster/files/14067505/Tomb.Raider.1.ATI.rar.txt)

Those savegames show up on the editor for me. I made quite a few updates, maybe check that you're using the [latest binary](https://github.com/JulianOzelRose/TR-SaveMaster/tree/master/TR-SaveMaster/bin/x64/Release).

![TR1](https://github.com/JulianOzelRose/TR-SaveMaster/assets/95890436/088aa59e-6e54-467b-9189-e4fa4bd7db89)
![TR1UB](https://github.com/JulianOzelRose/TR-SaveMaster/assets/95890436/c7a8900a-81f0-4fac-930e-f27799bd6d5a)

**Comment by StenApp** [comment]
I used the latest now (https://github.com/JulianOzelRose/TR-SaveMaster/commit/0dc28b3581ad6dade5f1a39847a5e09d50087708)

but...
![2024-01-26 21_09_16-Greenshot](https://github.com/JulianOzelRose/TR-SaveMaster/assets/32524257/c286060f-a41e-41bc-9aaf-0e3efff2cd8d)

I installed Gog TR1 and installed TombATI, maybe this makes the difference
https://www.glidos.net/tombati.html

**Comment by JulianOzelRose** [comment]
Ah, I see the problem. The level index of UB saves causes a false positive for TR1 savegames, so I used file size to differentiate them. Try it now, it shouldn't mix TR1 and UB savegames anymore.

**Comment by StenApp** [comment]
This Version fixes it, thanks!
I'm playing TR3 right now, so i think for the first we can close this as done
